--
CREATE TABLE Student(
StuID	VARCHAR(50) NOT NULL PRIMARY KEY,
FName NVARCHAR(50) NOT NULL,
LName NVARCHAR(50) NOT NULL,
Major VARCHAR(50) NOT NULL,
Gender bit NOT NULL,
PhoneNumber	VARCHAR(50) NOT NULL,
);

--
CREATE TABLE Lecturer(
LID VARCHAR(50) NOT NULL PRIMARY KEY,
FName NVARCHAR(50) NOT NULL,
LName NVARCHAR(50) NOT NULL,
[Address] NVARCHAR(150) NOT NULL,
Gender BIT NOT NULL,
PhoneNumber int NOT NULL,
);

--
CREATE TABLE [Subject](
SubID VARCHAR(50) NOT NULL PRIMARY KEY,
SubName VARCHAR(150) NOT NULL,
);

--
CREATE TABLE Semester(
SemID VARCHAR(50) NOT NULL PRIMARY KEY,
SemName VARCHAR(150) NOT NULL,
);

CREATE TABLE Class(
ClassID VARCHAR(50) NOT NULL PRIMARY KEY ,
ClassName VARCHAR(50) NOT NULL,
);

drop table CLASS_Semester
CREATE TABLE CLASS_Semester(
ClassID VARCHAR(50) NOT NULL ,
SemID VARCHAR(50) NOT NULL,
CONSTRAINT pk_CLASS_Semester PRIMARY KEY (ClassID,SemID),
CONSTRAINT fk_CLASS_Semester1 FOREIGN KEY (ClassID) REFERENCES Class(ClassID),
CONSTRAINT fk_CLASS_Semester2 FOREIGN KEY (SemID) REFERENCES Semester(SemID),
);
--

Drop table [Group]
CREATE TABLE [Group](
GID VARCHAR(50) NOT NULL PRIMARY KEY,
LID VARCHAR(50) NOT NULL,
SubID VARCHAR(50) NOT NULL,
ClassID VARCHAR(50) NOT NULL,
CONSTRAINT fk_Group FOREIGN KEY (LID)  REFERENCES Lecturer(LID),
CONSTRAINT fk_Group1 FOREIGN KEY (SubID) REFERENCES [Subject](SubID),
CONSTRAINT fk_group2 FOREIGN KEY (ClassID) REFERENCES Class(ClassID),
);


--
CREATE TABLE Group_Student(
StuID VARCHAR(50) NOT NULL,
GID VARCHAR(50) NOT NULL,

CONSTRAINT pk_Group_Student PRIMARY KEY (StuID, GID),
CONSTRAINT fk_Student1 FOREIGN KEY (StuID) REFERENCES Student(StuID),
CONSTRAINT fk_Group1 FOREIGN KEY (GID) REFERENCES [Group](GID),
);
drop table Group_Student
--
CREATE TABLE Assesment(
AssID VARCHAR(50) NOT NULL PRIMARY KEY,
[Type] VARCHAR(150) NOT NULL,
Part INT NOT NULL,
[Weight] INT NOT NULL,
[Completion Criteria] INT NOT NULL,
[Knowledge and Skill] VARCHAR(150) NOT NULL,
NOTE VARCHAR,
);

--
CREATE TABLE Assesment_Subject(
SubID VARCHAR(50) NOT NULL,
AssID VARCHAR(50) NOT NULL,
[Weight] INT NOT NULL,
TypeID varchar(50),
Duration VARCHAR NOT NULL,

CONSTRAINT pk_Assesment_Subject PRIMARY KEY (SubID, AssID),
CONSTRAINT fK_Subject FOREIGN KEY (SubID) REFERENCES [Subject](SubID),
CONSTRAINT fk_Assesment FOREIGN KEY (AssID) REFERENCES Assesment(AssID),
);

--
CREATE TABLE Grade(

StuID VARCHAR(50) NOT NULL,
SubID VARCHAR(50) NOT NULL,
AssID VARCHAR(50) NOT NULL,
LID VARCHAR(50) NOT NULL,
Mark FLOAT NOT NULL,

CONSTRAINT Check_Mark CHECK (Mark >= 0 and Mark <= 10),
CONSTRAINT pk_Grade PRIMARY KEY  (StuID, SubID),
CONSTRAINT fk_Grade1 FOREIGN KEY (StuID) REFERENCES Student(StuID),
CONSTRAINT fk_Grade2 FOREIGN KEY (SubID) REFERENCES [Subject](SubID),
CONSTRAINT fk_Grade3 FOREIGN KEY (AssID) REFERENCES Assesment(AssID),
CONSTRAINT fk_Grade4 FOREIGN KEY (LID) REFERENCES Lecturer(LID),
);



CREATE TABLE Student_Class(
StuID VARCHAR(50) NOT NULL,
GID VARCHAR(50) NOT NULL,
CONSTRAINT pk_Student_Class PRIMARY KEY (StuID, GID),
CONSTRAINT fk_Student_Class FOREIGN KEY (StuID) REFERENCES Student(StuID),
CONSTRAINT fk_Group1 FOREIGN KEY (GID) REFERENCES [Group](GID),
);


CREATE table Category(
TypeID varchar(50) PRIMARY KEY, 
Decription varchar(150),
);